%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 360
distortion_parameters:
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
projection_parameters:
  fx: 271.18487548828125
  fy: 271.18487548828125
  cx: 314.42938232421875
  cy: 175.3916015625
